In [2]:
%%bash
ls

Projet3.ipynb
regulatory_seq_PHO.fasta
regulatory_seqs_GAL.fasta
regulatory_seqs_MET.fasta
yeast_s_cerevisae_genomic_chr1-4.fna


In [8]:
import projet

In [13]:
projet.read_fasta("regulatory_seq_PHO.fasta")

ERROR:root:
UnicodeDecodeError while processing traceback.



NameError: name 'nucleobase_undetermine' is not defined

In [102]:
import io
import math
import numpy as np
import copy

#Définition des nucléotides
nucleotide = {'A':0,'C':1,'G':2,'T':3}
nucleotide_inverse = {0:'A',1:'C',2:'G',3:'T'}
nucleotide_indetermine = {'A':0,'C':1,'G':2,'T':3,'N':-1}

def decode_sequence(sequence):
    inv_nucleotide = {v:k for k, v in nucleotide_indetermine.items()}
    to_str = ""
    for i in sequence:
        if(i in inv_nucleotide):
            to_str += inv_nucleotide[i]
        else:
            to_str += 'N'
    return to_str
    

def encode_sequence(string):
    to_list = []
    for base in string:
        if(base in nucleotide_indetermine):
            to_list.append(nucleotide_indetermine[base])
    return to_list

def read_fasta(fasta_filepath):
    fasta_file = io.open(fasta_filepath, 'r')
    current_sequence = ""
    sequences_dict = {}
    for line in fasta_file.readlines():
        if(line[0] == '>'):
            current_sequence = line
            sequences_dict[line] = []
        else:
            for nucl in line:
                if(nucl in nucleotide_indetermine):
                    sequences_dict[current_sequence].append(nucleotide_indetermine[nucl])
    

    return sequences_dict
    
def nucleotide_count(sequence):
    count = [0 for k in nucleotide]
    for nucl in sequence:
        if(nucl >= 0):
            count[nucl] += 1
    return count

def nucleotide_frequency(sequence):
    count = [0 for k in nucleotide]
    n_nucl = 0.
    for nucl in sequence:
        if(nucl >= 0):
            count[nucl] += 1
            n_nucl += 1.
    return count/(np.sum(count))

def log_proba_sequence(liste_freq):
    proba = 1
    for i in liste_freq:
        proba *= i
    return math.log(proba)

def count_word(k, sequence):
    res = {}
    
    for i in range(len(sequence)-k+1):
        mot = sequence[i:i+k]
        string = ""
        for s in mot:
            string += nucleotide_inverse[s]
        if string in res.keys():
            res[string] += 1
        else:
            res[string] = 1
            
    return res
        
    
def probaCondi(frequences, mot):
    reverseMot = copy(mot)
    reverseMot.reverse()
    characters = list(reverseMot)
    proba = 1
    for i in range(0, len(characters)):
        proba *= frequences[nucleotide[characters[0]]]
    return proba
    
def comptage_attendu(sequence, frequences, k, l):
    #UTILISER LOGPROBA
    result = {}
    mots = count_word(k, sequence).keys()
    for mot in mots:
        result[mot] = probaCondi(frequences, mot)*l
    return result

In [95]:
sequence = read_fasta("regulatory_seq_PHO.fasta")
nom = list(sequence.keys())


In [96]:
complet = []
for k in nom:
    complet = complet + sequence[k]
    print(k, nucleotide_count(sequence[k]))
    print(nucleotide_frequency(sequence[k]))
    print(log_proba_sequence(nucleotide_frequency(sequence[k])))
    print("\n\n")
sequence["complet"] = complet
sequenceLength = nucleotide_count(sequence["complet"])
letterFrequency = nucleotide_frequency(sequence["complet"])
sequenceLog = log_proba_sequence(nucleotide_frequency(sequence["complet"]))

>PHO81	PHO81; upstream from -800 to -1; size: 800; feature type:cds; location: Saccharomyces_cerevisiae:NC_001139.8:958214:959013:R
 [251, 145, 145, 259]
[0.31375 0.18125 0.18125 0.32375]
-5.702698424999239



>PHO11	PHO11; upstream from -800 to -1; size: 800; feature type:cds; location: Saccharomyces_cerevisiae:NC_001133.7:224651:225450:D
 [289, 145, 139, 227]
[0.36125 0.18125 0.17375 0.28375]
-5.735862529526608



>PHO84	PHO84; upstream from -800 to -1; size: 800; feature type:cds; location: Saccharomyces_cerevisiae:NC_001145.2:25802:26601:R
 [269, 182, 136, 213]
[0.33625 0.2275  0.17    0.26625]
-5.665781792547597



>PHO8	PHO8; upstream from -800 to -1; size: 800; feature type:cds; location: Saccharomyces_cerevisiae:NC_001136.8:1420243:1421042:R
 [267, 162, 198, 173]
[0.33375 0.2025  0.2475  0.21625]
-5.6220432918467615



>PHO5	PHO5; upstream from -800 to -1; size: 800; feature type:cds; location: Saccharomyces_cerevisiae:NC_001134.7:430946:431745:R
 [255, 160, 158, 227]
[0.31875 

In [81]:
count_word(4, sequence[nom[0]])

{'AAAA': 12,
 'AAAC': 3,
 'AAAG': 3,
 'AAAT': 8,
 'AACA': 5,
 'AACC': 4,
 'AACG': 6,
 'AACT': 4,
 'AAGA': 6,
 'AAGC': 1,
 'AAGG': 2,
 'AAGT': 5,
 'AATA': 5,
 'AATC': 5,
 'AATG': 3,
 'AATT': 11,
 'ACAA': 9,
 'ACAG': 3,
 'ACAT': 5,
 'ACCA': 3,
 'ACCC': 1,
 'ACCG': 1,
 'ACCT': 2,
 'ACGA': 1,
 'ACGC': 3,
 'ACGT': 7,
 'ACTA': 7,
 'ACTG': 2,
 'ACTT': 2,
 'AGAA': 8,
 'AGAC': 2,
 'AGAG': 4,
 'AGAT': 3,
 'AGCA': 6,
 'AGCC': 1,
 'AGCG': 1,
 'AGCT': 4,
 'AGGC': 2,
 'AGGG': 2,
 'AGGT': 5,
 'AGTA': 2,
 'AGTC': 2,
 'AGTG': 1,
 'AGTT': 5,
 'ATAA': 8,
 'ATAC': 3,
 'ATAG': 5,
 'ATAT': 6,
 'ATCA': 7,
 'ATCG': 1,
 'ATCT': 5,
 'ATGA': 3,
 'ATGC': 2,
 'ATGG': 3,
 'ATGT': 3,
 'ATTA': 8,
 'ATTC': 3,
 'ATTG': 7,
 'ATTT': 9,
 'CAAA': 6,
 'CAAC': 7,
 'CAAG': 8,
 'CAAT': 4,
 'CACA': 3,
 'CACG': 2,
 'CACT': 3,
 'CAGA': 1,
 'CAGC': 4,
 'CAGG': 2,
 'CAGT': 2,
 'CATA': 4,
 'CATC': 3,
 'CATG': 2,
 'CATT': 3,
 'CCAA': 1,
 'CCAC': 2,
 'CCAT': 1,
 'CCCT': 3,
 'CCGC': 1,
 'CCGT': 2,
 'CCTA': 4,
 'CCTC': 2,
 'CCTT': 5,
 '

In [103]:
comptage_attendu([0,1,2,3], [0.25,0.25,0.25,0.25], 2, 4)

TypeError: 'module' object is not callable